version: '3.8'
services:
  criteria-postgresql:
    image: postgres:latest
    # volumes:
    #     - ~/volumes/jhipster/schoolservice/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=criteria
      - POSTGRES_USER=criteria
      - POSTGRES_PASSWORD=criteria
    ports:
      - 5455:5432
